<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div class="instruction">
        <strong>Informe os dados do parcelamento</strong>
    </div>

    <input type="hidden" id="proposal_id" name="payment[proposal_id]" />

    <li>
        <label class="required" for="payment_form_<?php echo $this->getMethodCode() ?>"><em>*</em><?php echo $this->__('Informe seu CPF') ?></label>
        <div class="input-box">
            <input type="text" id="paymee_document_boleto" name="payment[paymee_cpf]" title="<?php echo $this->__('CPF') ?>" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getInfoData('cpf')) ?>" maxlength="16"/>
        </div>
    </li>

    <?php $bancos = Mage::helper('juniormaia_paymee')->getBanks(); ?>
    <li>
        <label class="required" for="payment_form_<?php echo $this->getMethodCode() ?>"><em>*</em><?php echo $this->__('Parcelas') ?></label>
        <div class="input-box">
            <select name="payment[paymee_boleto_installments]" id="paymee_boleto_installments" class="select required-entry">
                <option value="">Informe o Cpf</option>
            </select>
        </div>
    </li>

</div>