<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div class="instruction">
        <strong>Dados da sua conta bancária</strong>
    </div>

    <?php $bancos = Mage::helper('juniormaia_paymee')->getBanks(); ?>
    <li>
        <label><?php echo $this->__('Banco') ?>*</label>
        <div class="input-box">
            <select name="payment[paymee_banco]">
                <?php
                foreach($bancos as $banco){
                    ?>
                    <option value="<?php echo $banco['value'] ?>"><?php echo $banco['name']?></option>
                    <?php
                }?>
            </select>
        </div>
    </li>
    <li>
        <label class="required"><em>*</em><?php echo $this->__('CPF ou CNPJ') ?></label>
        <div class="input-box">
            <input type="text" id="paymee_document" name="payment[paymee_cpf]" title="<?php echo $this->__('CPF') ?>" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getInfoData('cpf')) ?>" maxlength="16"/>
        </div>
    </li>
    <li>
        <label class="required"><em>*</em><?php echo $this->__('Agência') ?></label>
        <div class="input-box">
            <input type="text" id="paymee_branch" name="payment[paymee_branch]" title="<?php echo $this->__('Branch') ?>" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getInfoData('branch')) ?>" maxlength="6"/>
        </div>
    </li>
    <li>
        <label class="required"><em>*</em><?php echo $this->__('Conta') ?></label>
        <div class="input-box">
            <input type="text" id="paymee_account" name="payment[paymee_account]" title="<?php echo $this->__('Account') ?>" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getInfoData('account')) ?>"/>
        </div>
    </li>
</div>