<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <input type="text" id="paymee_banco" name="payment[paymee_banco]" value="PIX" style="display: none;"/>
    <li>
        <label class="required"><em>*</em><?php echo $this->__('CPF ou CNPJ') ?></label>
        <div class="input-box">
            <input type="text" id="paymee_document" name="payment[paymee_cpf]" title="<?php echo $this->__('CPF') ?>" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getInfoData('cpf')) ?>" maxlength="16"/>
        </div>
    </li>
</div>