<div class="paymee-instructions">
    <?php $paymeeInstructions = Mage::getSingleton('core/session')->getData('paymee_instructions'); ?>
    <?php
    $responsePaymee = json_decode($paymeeInstructions, true);

    $body   =  $responsePaymee['response'];
    $steps  = $body['instructions']['steps'];
    $uuid   = $body['uuid'];
    ?>
    <div class="instructions">

        <?php if ($body['instructions']['name'] != 'PIX'): ?>
            <h1>Dados para transferência</h1>
        <?php else: ?>
            <h1>Pagamento via PIX</h1>
        <?php endif; ?>

        <?php if ($body['instructions']['name'] != 'PIX'): ?>
            <ul>
                <li><span>Banco: <strong><?php echo $body['instructions']['name'] ?></strong></span></li>
                <li><span>Agência: <strong><?php echo $body['instructions']['beneficiary_branch'] ?></strong></span></li>
                <li><span>Conta-Corrente: <strong><?php echo $body['instructions']['beneficiary_account'] ?></strong></span></li>
                <li><span>Favorecido: <strong><?php echo $body['instructions']['beneficiary_name'] ?></strong></span></li>
                <li><span>Valor: <strong>R$ <?php echo number_format($body['amount'], 2, ',', '.') ?></strong></span></li>
                <div class="advice">
                    <span>Realize a transferência bancária no valor exato do seu pedido.</span>
                </div>
                <div class="buttons-set">
                    <a type="button" title="<?php echo $this->__('IR PARA INTERNET BANKING') ?>" class="button"
                       href="<?php echo $body['instructions']['redirect_urls']['desktop'] ?>" target="_blank">
                        <span>
                            <span>
                                <?php echo $this->__('IR PARA INTERNET BANKING') ?>
                            </span>
                        </span>
                    </a>
                </div>
            </ul>
        <?php else: ?>
            <?php
            $qrcode = $body['instructions']['qrCode']['url'];
            $plain  = $body['instructions']['qrCode']['plain'];
            ?>
            <div class="box-paymee">
                <img
                        id='barcode'
                        class="paymee-img-qr"
                        src="https://api.qrserver.com/v1/create-qr-code/?data='<?php echo $qrcode; ?>'&amp;size=200x200"
                        alt=""
                        title="PayMee"
                        width="200"
                        height="200" />
                <span class="qr-subtitle">Ler com seu aplicativo bancário</span>
            </div>
            <div class="box-paymee">
                <img
                        src="https://www.bcb.gov.br/content/estabilidadefinanceira/piximg/logo_pix.png"
                        class="paymee-img-pix"
                        width="280"
                        height="100"
                />
            </div>

            <input type="text" class="paymee-textBox" value="<?php echo $body['instructions']['name']; ?>" id="paymee-method">
            <input type="text" class="paymee-textBox" value="<?php echo $plain; ?>" id="plain">
            <input type="text" class="paymee-textBox" value="<?php echo $uuid; ?>" id="uuid">
            <input type="text" class="paymee-textBox" value="<?php echo Mage::getUrl('paymee/checkout/checkPix', array('_secure' => true)); ?>" id="paymee-url">
            <input type="text" class="paymee-textBox" value="<?php echo Mage::getUrl('customer/account/'); ?>" id="customer-url">
            <button class="btn-paymee" onclick="copyPlain()">Copiar Código</button>
            <div class="buttons-set-pedidos">
                <a type="button" title="<?php echo $this->__('IR PARA MEUS PEDIDOS') ?>" class="button"
                   href="<?php echo Mage::getUrl('customer/account/'); ?>" target="_blank">
                        <span>
                            <span>
                                <?php echo $this->__('IR PARA MEUS PEDIDOS') ?>
                            </span>
                        </span>
                </a>
            </div>
        <?php endif; ?>
    </div>
</div>

<script>
    function copyPlain() {
        var copyText = document.getElementById("plain");
        copyText.select();
        copyText.setSelectionRange(0, 99999)
        document.execCommand("copy");
        alert("Código para pagamento copiado com sucesso!");
    }
</script>